name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install
      run: npm i
    - name: Lint JS/TS
      run: npm run lint
    - name: Lint CSS
      run: npm run lint:css
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install
      run: npm i
    - name: Lint
      run: npm run test:once
